#!/usr/bin/env bash
case "$IDEFIX_COMPILER" in
    icc)
        source /opt/intel/oneapi/setvars.sh;;
    gricad-*)
        function remote-tests() {
            printf "Running tests : %s\n" "$*"
        }
        function run-tests() {
            local -a args=( "$@" )
            ssh workflow "$(declare -p args); $(declare -f remote-tests); "'remote-tests "${args[@]}"'
        }
    ;;
    *)
        function run-tests() {
            cd "$1"
            ./testme.py "${@:2}"
        }
        ;;
esac

set -ue
run-tests "$@"
