#!/usr/bin/env bash
declare -p GITHUB_REPOSITORY GITHUB_SHA

action="$1"; shift
case "$action" in
    worker-checkout)
        vars=( GITHUB_REPOSITORY GITHUB_SHA )
        function remote-command() {
            local local_checkout="$PWD/.github-runner/$GITHUB_SHA"
            if [ ! -e "$local_checkout" ]; then
                (
                    mkdir -p "$local_checkout"
                    cd "$local_checkout"
                    git init
                    git remote add origin "https://github.com/$GITHUB_REPOSITORY"
                    git fetch origin "$GITHUB_SHA"
                    git reset --hard "$GITHUB_SHA"
                    git submodule update --quiet --init --depth=1
                )
            fi
        }
        ;;
    run-tests)
        vars=( GITHUB_SHA IDEFIX_COMPILER  )
        function remote-command() {
            local local_checkout="$PWD/.github-runner/$GITHUB_SHA"
            cd "$local_checkout"
            export IDEFIX_DIR="$PWD"
            printf "Running command in %s : %s\n" "$IDEFIX_DIR" "$*"
            printf "Entering directory %s from %s\n" "$1" "$PWD"
            cd "$1"
            in-env declare -p LD_LIBRARY_PATH PWD
        }
        ;;
    *)
        vars=( )
        function remote-command() {
            :
        }
        ;;
esac

args=( "$@" )

source "$HOME/env/$IDEFIX_COMPILER.sh"
ssh "$IDEFIX_COMPILER-worker" \
    bash -s <<EOF
$(declare -p "${vars[@]}")
$(declare -f remote-command export-env in-env)
$(declare -p args)
$(export-env)
remote-command \"\${args[@]}\"
EOF
