name: Idefix CIs
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.0
        if: always()

  gcc-jobs:
    needs: Linter
    name: CPU Jobs (gcc)
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -Werror
      IDEFIX_COMPILER: gcc
      IDEFIX_RUNNER: shallow

  icc-jobs:
    needs: Linter
    name: CPU Jobs (Intel)
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -intel -Werror
      IDEFIX_COMPILER: icc
      IDEFIX_RUNNER: shallow

  cuda-jobs:
    needs: Linter
    name: GPU Jobs (CUDA)
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -cuda -Werror
      IDEFIX_COMPILER: cuda
      IDEFIX_RUNNER: shallow

  hip-jobs:
    needs: Linter
    name: GPU Jobs (AMD)
    uses: ./.github/workflows/idefix-ci-jobs.yml
    with:
      TESTME_OPTIONS: -hip -Werror
      IDEFIX_COMPILER: hip
      IDEFIX_RUNNER: shallow
